# Generated by Django 4.2 on 2026-05-24 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('headquarters', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='RawIngestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel/Procurement'), ('UTILITY', 'Utility CSV'), ('TRAVEL', 'Corporate Travel (Concur)')], max_length=20)),
                ('raw_data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PARSED', 'Parsed Successfully'), ('FAILED', 'Failed to Parse'), ('APPROVED', 'Approved for Audit'), ('REJECTED', 'Rejected by Analyst')], default='PENDING', max_length=20)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_ingestions', to='ingestion.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel/Procurement'), ('UTILITY', 'Utility CSV'), ('TRAVEL', 'Corporate Travel (Concur)')], max_length=20)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions'), ('SCOPE_2', 'Scope 2 - Purchased Energy'), ('SCOPE_3', 'Scope 3 - Value Chain')], max_length=20)),
                ('category', models.CharField(choices=[('FUEL_DIESEL', 'Diesel (Scope 1)'), ('FUEL_GASOLINE', 'Gasoline (Scope 1)'), ('FUEL_NATURAL_GAS', 'Natural Gas (Scope 1)'), ('FUEL_COAL', 'Coal (Scope 1)'), ('PROCUREMENT_MATERIALS', 'Raw Materials (Scope 3)'), ('PROCUREMENT_PACKAGING', 'Packaging (Scope 3)'), ('ELECTRICITY', 'Electricity (Scope 2)'), ('TRAVEL_FLIGHTS', 'Business Flights (Scope 3)'), ('TRAVEL_HOTEL', 'Hotel Stays (Scope 3)'), ('TRAVEL_GROUND', 'Ground Transport (Scope 3)')], max_length=50)),
                ('quantity_kg_co2e', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('quantity_value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('quantity_unit', models.CharField(choices=[('KG', 'Kilograms'), ('TONNE', 'Metric Tonnes (1000 kg)'), ('LITRE', 'Litres'), ('M3', 'Cubic Meters'), ('KWH', 'Kilowatt Hours'), ('KM', 'Kilometres'), ('MILES', 'Miles'), ('NIGHT', 'Hotel Nights')], max_length=20)),
                ('unit_conversion_factor', models.DecimalField(decimal_places=6, help_text='Applied to convert to CO2e', max_digits=10)),
                ('activity_date', models.DateField(help_text='Date of actual activity')),
                ('billing_period_start', models.DateField(blank=True, help_text='For utilities: period start', null=True)),
                ('billing_period_end', models.DateField(blank=True, help_text='For utilities: period end', null=True)),
                ('facility', models.CharField(blank=True, help_text="e.g., 'Plant A', 'HQ Building'", max_length=255, null=True)),
                ('vendor_supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, help_text="e.g., airport code 'ORD'", max_length=100, null=True)),
                ('destination', models.CharField(blank=True, help_text="e.g., airport code 'SEA'", max_length=100, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flagged_anomaly', models.CharField(choices=[('NONE', 'No Issues'), ('UNIT_MISMATCH', 'Unit conversion unclear'), ('MISSING_FACTOR', 'Emission factor missing'), ('OUTLIER', 'Value significantly outside normal range'), ('DATE_INCONSISTENT', 'Date inconsistent with period'), ('DUPLICATE_LIKELY', 'Likely duplicate record')], default='NONE', max_length=50)),
                ('analyst_notes', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Analyst Review'), ('APPROVED', 'Approved for Audit'), ('REJECTED', 'Rejected - See Notes'), ('NEEDS_CLARIFICATION', 'Needs Clarification')], default='PENDING_REVIEW', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_emissions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_emissions', to='ingestion.company')),
                ('data_source_ingestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_emissions', to='ingestion.rawingestion')),
            ],
            options={
                'verbose_name_plural': 'Normalized Emissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('INGESTED', 'Raw data ingested'), ('PARSED', 'Data parsed to normalized'), ('APPROVED', 'Analyst approved'), ('REJECTED', 'Analyst rejected'), ('FLAGGED', 'Anomaly flagged'), ('UNFLAGGED', 'Anomaly unflagged'), ('NOTES_ADDED', 'Analyst notes added')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('details_json', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ingestion.company')),
                ('related_emission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.normalizedemission')),
                ('related_ingestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.rawingestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='rawingestion',
            index=models.Index(fields=['company', 'source_type', 'status'], name='ingestion_r_company_3d6404_idx'),
        ),
        migrations.AddIndex(
            model_name='rawingestion',
            index=models.Index(fields=['uploaded_at'], name='ingestion_r_uploade_6d6eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemission',
            index=models.Index(fields=['company', 'approval_status'], name='ingestion_n_company_12c61a_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemission',
            index=models.Index(fields=['activity_date'], name='ingestion_n_activit_2964fe_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemission',
            index=models.Index(fields=['scope'], name='ingestion_n_scope_e1323f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'timestamp'], name='ingestion_a_company_1d4912_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='ingestion_a_action_a594b7_idx'),
        ),
    ]
